services:
  - type: web
    name: warrn
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: warrn-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.0

databases:
  - name: warrn-db
    databaseName: warrn
    user: warrn
    region: oregon
